name: Deploy Node.js App to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo (optional, if needed locally)
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PEM_KEY }}" > ~/.ssh/ec2-key.pem
        chmod 600 ~/.ssh/ec2-key.pem

    - name: Run deployment script on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2-key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
        #!/bin/bash
        set -e

        # Update system
        sudo apt update -y
        sudo apt upgrade -y

        # Install Node.js 18.x
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt install -y nodejs

        # Install git
        sudo apt install -y git

        # Clone the repository
        sudo rm -rf /opt/nodejs-app
        sudo git clone https://github.com/pdevulapally/Preetham-Project.git /opt/nodejs-app

        # Install npm dependencies and copy env file
        cd /opt/nodejs-app
        aws s3 cp s3://preetham-project-env-files/node.env .env
        source .env
        printenv | sort
        npm install

        sudo systemctl restart nodejs-app
        EOF
